### ISSUE TITLE
Set ContentType when upload the image 

### ISSUE THREAD

**Issue by somarlyonks** [CSS-ZEN/screenshot#9]
AWS S3 will set the content type to `application/octet-stream` on default. It works for most circumstances, but `next/image` will complain about ContentType.

https://github.com/vercel/next.js/blob/288984b1ea843465069ffa54fda048d9a745872c/packages/next/next-server/server/image-optimizer.ts#L269

Better to set ContentType at

https://github.com/CSS-ZEN/screenshot/blob/90a6e5deabf53366fe777da5459ba7e842b63b03/src/helpers/uploadAws.ts#L10

```diff
 10        Body: fileBuffer,
+11        ContentType: 'image/jpeg',
 12    }
```

**Comment by bestenevoy** [comment]
get
